FROM node:lts-alpine3.20@sha256:eb8101caae9ac02229bd64c024919fe3d4504ff7f329da79ca60a04db08cef52
EXPOSE 8080

ENV NODE_ENV=development
WORKDIR /usr/src/app

COPY --chown=node:node package.json .
RUN npm install

COPY --chown=node:node . .

USER node
CMD [ "npm","run","serve" ]